export const ADMIN_ROUTE = '/admin';
export const LOGIN_ROUTE = '/login';
export const REGISTRATION_ROUTE = '/registration';
export const MAIN_ROUTE = '/';
export const SHOP_ROUTE = '/shop';
export const BASKET_ROUTE = '/basket';
export const THING_ROUTE = '/thing';
export const TERMS_ROUTE = '/terms';
export const PRIVACY_ROUTE = '/privacy';
export const PAYMENT_ROUTE = '/payment';
export const USERINFO_ROUTE = '/user/:id';
export const USER_ACCOUNT_ROUTE = '/account';
export const ALL_ORDERS_ROUTE = '/admin/orders';
export const ALL_USERS_ROUTE = '/admin/users';
export const ALL_RETURNS_ROUTE = '/admin/returns';
export const EXCHANGE_ROUTE = '/exchange/:thingId';
export const ALL_EXCHANGES_ROUTE = '/admin/exchanges'; // Добавляем маршрут для просмотра всех обменов администратором
