export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/main'
export const SHOP_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const THING_ROUTE = '/thing'